### ISSUE TITLE
07-14 02:38:45 INFO     start: minimum_bounding_geometry 07-14 02:38:46 WARNING  The Advanced/ArcInfo license level of ArcGIS is not available. A slight modification to the minimum bounding geometry process is necessary to ensure FTOT can successfully run.

### ISSUE THREAD

**Issue by Kamol-Roy** [VolpeUSDOT/FTOT-Public#39] opened 2022-07-14 06:45 UTC
Report is not being generated because of the above mentioned warning? Could anyone mention what slight modification is needed?

**Comment by aobergdc** [comment] 2022-07-14 13:00
Hi @Kamol-Roy-- thanks for reaching out. No action should be necessary on your part due to this warning. It sounds like you are running FTOT using one of the lower level licenses of ArcGIS Pro (Basic or Standard). For full FTOT functionality, we strongly recommend using an Advanced license. However, if not using an Advanced license, FTOT will warn when it is doing something different to work with a Basic or Standard license (it does this automatically with no user action required). FTOT should still function with a Basic or Standard license, but unexpected behavior and/or performance issues may emerge, and support is more limited.

Does to make sure everything is working, is FTOT providing additional logging beyond this warning message? If not, it might be worth double checking that your ArcGIS Pro license is active and running, and confirm the version you are running.

Let us know if you'd like to join our FTOT Users Group if you are interested in a quarterly update/telcon on FTOT features and new functionality.

**Comment by Kamol-Roy** [comment] 2022-07-15 22:52
Thank you @aobergdc for the quick response! Yes, please find below the full log from "C:\FTOT\scenarios\quick_start\qs1_rmp_dest\Default\logs":

07-15 18:51:01.139 INFO     =================================================================================
07-15 18:51:01.139 INFO     ============= FTOT RUN STARTING.  Run Option = O2 ===============================
07-15 18:51:01.140 INFO     =================================================================================
07-15 18:51:01.159 DEBUG    start: load_scenario_config_file
07-15 18:51:01.163 DEBUG    validate XML scenario against XML schema
07-15 18:51:01.163 DEBUG    initialize scenario object
07-15 18:51:01.163 DEBUG    validate schema version is correct
07-15 18:51:01.164 DEBUG    Replace any commas in the scenario name with dashes to accomodate csv files.
07-15 18:51:01.165 DEBUG    test: setting the default units with pint
07-15 18:51:01.166 DEBUG    PASS: setting the default units with pint
07-15 18:51:01.166 DEBUG    test: setting the vehicle loads for solid phase of matter with pint
07-15 18:51:01.166 DEBUG    test: setting the vehicle loads for liquid phase of matter with pint
07-15 18:51:01.168 DEBUG    PASS: setting the vehicle loads with pint passed
07-15 18:51:01.168 DEBUG    test: setting the vehicle fuel efficiencies with pint
07-15 18:51:01.169 DEBUG    PASS: setting the vehicle fuel efficiencies with pint passed
07-15 18:51:01.169 DEBUG    test: setting the vehicle emission factors with pint
07-15 18:51:01.172 DEBUG    PASS: setting the vehicle emission factors with pint passed
07-15 18:51:01.172 DEBUG    test: setting the base costs for rail with pint
07-15 18:51:01.173 DEBUG    PASS: setting the base costs for rail with pint passed
07-15 18:51:01.174 DEBUG    test: setting the base costs for truck with pint
07-15 18:51:01.175 DEBUG    PASS: setting the base costs for truck with pint passed
07-15 18:51:01.176 DEBUG    test: setting the base costs for barge with pint
07-15 18:51:01.176 DEBUG    PASS: setting the base costs for barge with pint passed
07-15 18:51:01.177 DEBUG    test: setting the transloading costs with pint
07-15 18:51:01.178 DEBUG    PASS: setting the transloading costs with pint passed
07-15 18:51:01.178 DEBUG    test: setting the artificial link distances with pint
07-15 18:51:01.179 DEBUG    PASS: setting the artificial link distances with pint passed
07-15 18:51:01.179 DEBUG    test: setting the short haul penalties with pint
07-15 18:51:01.180 DEBUG    PASS: setting the short haul penalties with pint passed
07-15 18:51:01.182 CONFIG   xml_scenario_name: 	QS1 - Default
07-15 18:51:01.182 CONFIG   xml_scenario_description: 	This scenario demonstrates simple movements from a RMP to a destination.
07-15 18:51:01.182 CONFIG   xml_scenario_run_directory: 	C:\FTOT\scenarios\quick_start\qs1_rmp_dest\Default
07-15 18:51:01.182 CONFIG   xml_scenario_schema_version: 	6.0.2
07-15 18:51:01.182 CONFIG   xml_common_data_folder: 	C:\FTOT\scenarios\common_data
07-15 18:51:01.182 CONFIG   xml_base_network_gdb: 	C:\FTOT\scenarios\common_data\networks\Public_Intermodal_Network_2019_3.gdb
07-15 18:51:01.182 CONFIG   xml_disruption_data: 	None
07-15 18:51:01.182 CONFIG   xml_base_rmp_layer: 	C:\FTOT\scenarios\quick_start\input_data\facilities.gdb\rmp
07-15 18:51:01.182 CONFIG   xml_base_destination_layer: 	C:\FTOT\scenarios\quick_start\input_data\facilities.gdb\dest
07-15 18:51:01.182 CONFIG   xml_base_processors_layer: 	None
07-15 18:51:01.182 CONFIG   xml_rmp_commodity_data: 	C:\FTOT\scenarios\quick_start\qs1_rmp_dest\Default\input_data\rmp.csv
07-15 18:51:01.182 CONFIG   xml_destinations_commodity_data: 	C:\FTOT\scenarios\quick_start\qs1_rmp_dest\Default\input_data\dest.csv
07-15 18:51:01.182 CONFIG   xml_processors_commodity_data: 	None
07-15 18:51:01.182 CONFIG   xml_processors_candidate_slate_data: 	None
07-15 18:51:01.183 CONFIG   xml_schedule_data: 	None
07-15 18:51:01.183 CONFIG   xml_commodity_mode_data: 	None
07-15 18:51:01.183 CONFIG   xml_commodity_density_data: 	None
07-15 18:51:01.183 CONFIG   xml_default_units_solid_phase: 	metric_ton
07-15 18:51:01.183 CONFIG   xml_default_units_liquid_phase: 	kilogallon
07-15 18:51:01.183 CONFIG   xml_truck_load_solid: 	24 metric_ton
07-15 18:51:01.183 CONFIG   xml_railcar_load_solid: 	82 metric_ton
07-15 18:51:01.183 CONFIG   xml_barge_load_solid: 	700 metric_ton
07-15 18:51:01.183 CONFIG   xml_truck_load_liquid: 	8 kilogallon
07-15 18:51:01.183 CONFIG   xml_railcar_load_liquid: 	28.5 kilogallon
07-15 18:51:01.183 CONFIG   xml_barge_load_liquid: 	2100 kilogallon
07-15 18:51:01.183 CONFIG   xml_pipeline_crude_load_liquid: 	3150 kilogallon
07-15 18:51:01.183 CONFIG   xml_pipeline_prod_load_liquid: 	3150 kilogallon
07-15 18:51:01.183 CONFIG   xml_solid_railroad_class_1_cost: 	0.047 usd / metric_ton / mile
07-15 18:51:01.184 CONFIG   xml_liquid_railroad_class_1_cost: 	0.14 usd / kilogallon / mile
07-15 18:51:01.184 CONFIG   xml_rail_dc_7: 	1.0
07-15 18:51:01.184 CONFIG   xml_rail_dc_6: 	1.3
07-15 18:51:01.184 CONFIG   xml_rail_dc_5: 	1.6
07-15 18:51:01.184 CONFIG   xml_rail_dc_4: 	1.9
07-15 18:51:01.184 CONFIG   xml_rail_dc_3: 	2.1
07-15 18:51:01.184 CONFIG   xml_rail_dc_2: 	2.4
07-15 18:51:01.184 CONFIG   xml_rail_dc_1: 	2.6
07-15 18:51:01.184 CONFIG   xml_rail_dc_0: 	10.0
07-15 18:51:01.184 CONFIG   xml_liquid_truck_base_cost: 	0.66 usd / kilogallon / mile
07-15 18:51:01.184 CONFIG   xml_solid_truck_base_cost: 	0.22 usd / metric_ton / mile
07-15 18:51:01.184 CONFIG   xml_truck_interstate: 	1.0
07-15 18:51:01.184 CONFIG   xml_truck_pr_art: 	1.1
07-15 18:51:01.184 CONFIG   xml_truck_m_art: 	1.2
07-15 18:51:01.184 CONFIG   xml_truck_local: 	1.3
07-15 18:51:01.184 CONFIG   xml_liquid_barge_cost: 	0.097 usd / kilogallon / mile
07-15 18:51:01.184 CONFIG   xml_solid_barge_cost: 	0.032 usd / metric_ton / mile
07-15 18:51:01.184 CONFIG   xml_water_high_vol: 	1.0
07-15 18:51:01.184 CONFIG   xml_water_med_vol: 	1.3
07-15 18:51:01.185 CONFIG   xml_water_low_vol: 	1.6
07-15 18:51:01.185 CONFIG   xml_water_no_vol: 	10.0
07-15 18:51:01.185 CONFIG   xml_solid_transloading_cost: 	12.35 usd / metric_ton
07-15 18:51:01.185 CONFIG   xml_liquid_transloading_cost: 	40.0 usd / kilogallon
07-15 18:51:01.185 CONFIG   xml_road_max_artificial_link_dist: 	5 mile
07-15 18:51:01.185 CONFIG   xml_rail_max_artificial_link_dist: 	5 mile
07-15 18:51:01.185 CONFIG   xml_water_max_artificial_link_dist: 	5 mile
07-15 18:51:01.185 CONFIG   xml_pipeline_crude_max_artificial_link_dist: 	5 mile
07-15 18:51:01.185 CONFIG   xml_pipeline_prod_max_artificial_link_dist: 	5 mile
07-15 18:51:01.186 CONFIG   xml_liquid_rail_short_haul_penalty: 	71.8 usd / kilogallon
07-15 18:51:01.186 CONFIG   xml_solid_rail_short_haul_penalty: 	23.9 usd / metric_ton
07-15 18:51:01.186 CONFIG   xml_liquid_water_short_haul_penalty: 	76.1 usd / kilogallon
07-15 18:51:01.186 CONFIG   xml_solid_water_short_haul_penalty: 	25.4 usd / metric_ton
07-15 18:51:01.186 CONFIG   xml_truckFuelEfficiency: 	7.4 mile / gallon
07-15 18:51:01.186 CONFIG   xml_bargeFuelEfficiency: 	5.0 mile / gallon
07-15 18:51:01.186 CONFIG   xml_railFuelEfficiency: 	10.15 mile / gallon
07-15 18:51:01.186 CONFIG   xml_CO2urbanUnrestricted: 	1550.19 gram / mile
07-15 18:51:01.186 CONFIG   xml_CO2urbanRestricted: 	1343.74 gram / mile
07-15 18:51:01.186 CONFIG   xml_CO2ruralUnrestricted: 	1360.18 gram / mile
07-15 18:51:01.186 CONFIG   xml_CO2ruralRestricted: 	1338.31 gram / mile
07-15 18:51:01.186 CONFIG   xml_railroadCO2Emissions: 	23.48 gram / metric_ton / mile
07-15 18:51:01.186 CONFIG   xml_bargeCO2Emissions: 	41.78 gram / metric_ton / mile
07-15 18:51:01.186 CONFIG   xml_pipelineCO2Emissions: 	0.0 gram / metric_ton / mile
07-15 18:51:01.186 CONFIG   xml_densityFactor: 	3.0209251842000007 metric_ton / kilogallon
07-15 18:51:01.186 CONFIG   xml_detailed_emissions: 	False
07-15 18:51:01.186 CONFIG   xml_ndrOn: 	False
07-15 18:51:01.187 CONFIG   xml_permittedModes: 	['road', 'rail', 'water', 'pipeline_crude_trf_rts', 'pipeline_prod_trf_rts']
07-15 18:51:01.187 CONFIG   xml_capacityOn: 	False
07-15 18:51:01.187 CONFIG   xml_backgroundFlowModes: 	[]
07-15 18:51:01.187 CONFIG   xml_minCapacityLevel: 	0.0
07-15 18:51:01.187 CONFIG   xml_unMetDemandPenalty: 	5000.0
07-15 18:51:01.187 DEBUG    checking consistency of scenario config file with previous step
07-15 18:51:03.514 INFO     START: setup PuLP problem
07-15 18:51:03.515 INFO     START: create_flow_vars
07-15 18:51:03.517 INFO     START: create_unmet_demand_vars
07-15 18:51:03.518 INFO     START: create_candidate_processor_build_vars
07-15 18:51:03.519 INFO     START: create_binary_processor_vertex_flow_vars
07-15 18:51:03.520 INFO     START: create_processor_excess_output_vars
07-15 18:51:03.522 DEBUG    START: create_opt_problem
07-15 18:51:03.526 INFO     check if candidate tables exist
07-15 18:51:03.526 INFO     check if candidate processors exist from proc.csv
07-15 18:51:03.527 DEBUG    number of candidate processors from proc.csv = 0
07-15 18:51:03.527 DEBUG    candidate tables present: 0, input processor candidates: 0
07-15 18:51:03.527 DEBUG    FINISHED: create_opt_problem
07-15 18:51:03.527 DEBUG    START: create_constraint_unmet_demand
07-15 18:51:03.528 DEBUG    FINISHED: create_constraint_unmet_demand and return the prob 
07-15 18:51:03.528 DEBUG    STARTING:  create_constraint_max_flow_out_of_supply_vertex
07-15 18:51:03.528 DEBUG    Length of flow_var: 0
07-15 18:51:03.528 DEBUG    FINISHED:  create_constraint_max_flow_out_of_supply_vertex
07-15 18:51:03.529 DEBUG    STARTING:  create_constraint_daily_processor_capacity
07-15 18:51:03.529 DEBUG    FINISHED:  create_constraint_daily_processor_capacity
07-15 18:51:03.529 DEBUG    STARTING:  create_primary_processor_vertex_constraints - conservation of flow
07-15 18:51:03.530 DEBUG    conservation of flow and commodity ratios, primary processor vertices:
07-15 18:51:03.530 INFO     Starting the execute
07-15 18:51:03.532 INFO     Done with the execute fetch all for :
07-15 18:51:03.532 INFO     execute for processor primary vertices, with their in and out edges - Total Runtime (HMS): 	00:00:00 	 
07-15 18:51:03.533 INFO     Starting the fetchall
07-15 18:51:03.533 INFO     fetchall processor primary vertices, with their in and out edges - Total Runtime (HMS): 	00:00:00 	 
07-15 18:51:03.534 DEBUG    FINISHED:  create_primary_processor_conservation_of_flow_constraints
07-15 18:51:03.534 DEBUG    STARTING:  create_constraint_conservation_of_flow
07-15 18:51:03.534 INFO     conservation of flow, storage vertices:
07-15 18:51:03.534 INFO     Starting the long step:
07-15 18:51:03.535 INFO     Starting the execute
07-15 18:51:03.536 INFO     Done with the execute fetch all for :
07-15 18:51:03.537 INFO     execute for storage vertices, with their in and out edges - Total Runtime (HMS): 	00:00:00 	 
07-15 18:51:03.538 INFO     Starting the fetchall
07-15 18:51:03.538 INFO     fetchall nodes with no location id, with their in and out edges - Total Runtime (HMS): 	00:00:00 	 
07-15 18:51:03.539 INFO     adding processor excess variabless to conservation of flow
07-15 18:51:03.540 INFO     total conservation of flow constraints created on nodes: 0
07-15 18:51:03.540 INFO     conservation of flow, nx_nodes:
07-15 18:51:03.541 INFO     Starting the long step:
07-15 18:51:03.541 INFO     Starting the execute
07-15 18:51:03.542 INFO     Done with the execute fetch all for :
07-15 18:51:03.542 INFO     execute for  nodes with no location id, with their in and out edges - Total Runtime (HMS): 	00:00:00 	 
07-15 18:51:03.543 INFO     Starting the fetchall
07-15 18:51:03.543 INFO     fetchall nodes with no location id, with their in and out edges - Total Runtime (HMS): 	00:00:00 	 
07-15 18:51:03.544 INFO     total conservation of flow constraints created on nodes: 0
07-15 18:51:03.544 DEBUG    FINISHED:  create_constraint_conservation_of_flow
07-15 18:51:03.545 INFO     FINISHED: setup PuLP problem
07-15 18:51:03.545 INFO     START: solve_pulp_problem
07-15 18:51:03.574 INFO     Completion code: 1; Solution status: Optimal; Best obj value found: None
07-15 18:51:03.574 INFO     completed calling prob.solve()
07-15 18:51:03.576 INFO     FINISH: prob.solve(): Runtime (HMS): 	00:00:00
07-15 18:51:03.576 RESULT   prob.Status: 	 Optimal
07-15 18:51:03.578 ERROR    !!!!!!!!!!!!!!!!!!!!!!!!!!!!! EXCEPTION RAISED !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
07-15 18:51:03.578 ERROR    Traceback (most recent call last):
07-15 18:51:03.579 ERROR      File "C:\FTOT\program\ftot.py", line 239, in <module>
07-15 18:51:03.580 ERROR        o2(the_scenario, logger)
07-15 18:51:03.580 ERROR      File "C:\FTOT\program\ftot_pulp.py", line 53, in o2
07-15 18:51:03.581 ERROR        prob = solve_pulp_problem(prob, the_scenario, logger)
07-15 18:51:03.581 ERROR      File "C:\FTOT\program\ftot_pulp.py", line 3395, in solve_pulp_problem
07-15 18:51:03.582 ERROR        float(value(prob_final.objective))))
07-15 18:51:03.583 ERROR    TypeError: float() argument must be a string or a number, not 'NoneType'
07-15 18:51:03.583 ERROR    !!!!!!!!!!!!!!!!!!!!!!!!!!!!! EXCEPTION RAISED !!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Kamol-Roy** [comment] 2022-07-19 03:30
other logs and debug:
[o1_log_2022_07_17_02-30-02.log](https://github.com/VolpeUSDOT/FTOT-Public/files/9137172/o1_log_2022_07_17_02-30-02.log)
[g_log_2022_07_17_02-29-17.log](https://github.com/VolpeUSDOT/FTOT-Public/files/9137173/g_log_2022_07_17_02-29-17.log)
[c_log_2022_07_17_02-26-22.log](https://github.com/VolpeUSDOT/FTOT-Public/files/9137174/c_log_2022_07_17_02-26-22.log)
[f_log_2022_07_17_02-26-10.log](https://github.com/VolpeUSDOT/FTOT-Public/files/9137175/f_log_2022_07_17_02-26-10.log)
[s_log_2022_07_17_02-25-53.log](https://github.com/VolpeUSDOT/FTOT-Public/files/9137176/s_log_2022_07_17_02-25-53.log)
[probsolve_capture.txt](https://github.com/VolpeUSDOT/FTOT-Public/files/9137181/probsolve_capture.txt)
[LP_output_c2 - Copy.txt](https://github.com/VolpeUSDOT/FTOT-Public/files/9137182/LP_output_c2.-.Copy.txt)

**Comment by aobergdc** [comment] 2022-07-19 19:18
Thanks, this is super helpful. Unfortunately, the log messages seem to suggest there is a bug associated with running FTOT on a basic/standard license of ArcGIS Pro. We plan to look further into this issue, but due to our more limited support for running FTOT on a Basic/Standard license of ArcGIS Pro, we currently do not have a timeline for a resolution. In the meantime, are you by any chance able to access an Advanced license level of ArcGIS Pro?

**Comment by aobergdc** [comment] 2022-08-23 18:48
Hi @Kamol-Roy This issue is now resolved and will be included in the next public release of FTOT (2022.3-- expected around October 1st).

**Closed by aobergdc** 2022-08-23 18:48 UTC
